settings:
  title: 'Status Page'
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: lmt-lv # unique identifier
    name: lmt.lv
    url: 'https://lmt.lv/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    
  - id: test-lmt-lv # unique identifier
    name: test.lmt.lv
    url: 'https://test.lmt.lv/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
   
  - id: karte-lmt-lv # unique identifier
    name: karte.lmt.lv
    url: 'https://test.lmt.lv/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

#   - id: blog-cloudflare-com
#     name: The Cloudflare Blog
#     url: 'https://blog.cloudflare.com/'
#     method: GET
#     expectStatus: 200
